pipeline {
    agent any

    environment {
        IMAGE_NAME = "08474/kubernetes-app"
        TAG = "${BUILD_NUMBER}"
        DOCKER_CREDS = "docker-hub-creds"
        KUBECONFIG = "/var/jenkins_home/.kube/config"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/unixanand/unixanand-cloud-free-cicd-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-hub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push $IMAGE_NAME:$TAG
                      docker logout
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                  kubectl apply -f K8s/streamlit-deployment.yaml --validate=false
                  kubectl set image deployment/streamlit-app streamlit=$IMAGE_NAME:$TAG
                  kubectl rollout status deployment/streamlit-app
                '''
            }
        }


    }   // closes stages
}       // closes pipeline
